"""
Cross-mod schema analysis for the active CTP2 reference set.

Reference mods:
  - AE
  - Cradle
  - Ages of Man

These are the canonical CTP2 schema donors. The Civ2 / MoMJR lane is separate
and should not be mixed into this reference set.
"""
import csv
import sqlite3
import sys
from pathlib import Path

DB_PATH  = r'C:\Users\user\.copilot\session-state\5cf6a694-6240-47f7-a998-f6bd4314f973\session.db'
CSV_DIR  = Path(r'H:\Program Files(x86)\Activision\Call To Power 2\Scenarios\mom\tools\roundtrip_csv')
TOOLS    = Path(r'H:\Program Files(x86)\Activision\Call To Power 2\Scenarios\mom\tools')
REF_MODS = ('ae', 'cradle', 'aom')

db = sqlite3.connect(DB_PATH)

# ------------------------------------------------------------------
# 1. Load reference EAV CSVs (already generated by ctp2_roundtrip.py)
# ------------------------------------------------------------------

db.execute("DROP TABLE IF EXISTS eav_data")
db.execute("""
CREATE TABLE eav_data (
    mod TEXT, file_type TEXT, block_id TEXT, seq INT,
    field_type TEXT, key TEXT, val TEXT
)""")

ref_files = {
    'ae_units_eav.csv':        ('ae',     'units'),
    'ae_advance_eav.csv':      ('ae',     'advance'),
    'ae_uniticon_eav.csv':     ('ae',     'uniticon'),
    'cradle_units_eav.csv':    ('cradle', 'units'),
    'cradle_advance_eav.csv':  ('cradle', 'advance'),
    'cradle_uniticon_eav.csv': ('cradle', 'uniticon'),
    'aom_units_eav.csv':       ('aom',    'units'),
    'aom_advance_eav.csv':     ('aom',    'advance'),
    'aom_uniticon_eav.csv':    ('aom',    'uniticon'),
}

for fname, (mod, ftype) in ref_files.items():
    p = CSV_DIR / fname
    if not p.exists():
        print(f"SKIP {fname}")
        continue
    rows = []
    with open(p, newline='', encoding='utf-8') as f:
        for r in csv.DictReader(f):
            rows.append((mod, ftype, r['block_id'], int(r['seq']),
                         r['type'], r['key'], r['val']))
    db.executemany("INSERT INTO eav_data VALUES (?,?,?,?,?,?,?)", rows)
    print(f"  loaded {fname}: {len(rows)} rows")

db.commit()

# ------------------------------------------------------------------
# 2. Schema frequency table: which fields appear in which mods
# ------------------------------------------------------------------

def schema_table(file_type: str):
    rows = db.execute("""
        SELECT key, field_type,
               SUM(CASE WHEN mod='ae'      THEN 1 ELSE 0 END)   ae,
               SUM(CASE WHEN mod='cradle'  THEN 1 ELSE 0 END)   cradle,
               SUM(CASE WHEN mod='aom'     THEN 1 ELSE 0 END)   aom,
               COUNT(DISTINCT block_id || '|' || mod)        uses,
               MIN(val)                                       sample
        FROM eav_data
        WHERE file_type=?
        GROUP BY key, field_type
        ORDER BY uses DESC
    """, (file_type,)).fetchall()
    return rows


def print_schema(file_type: str):
    rows = schema_table(file_type)
    print(f"\n=== {file_type.upper()} schema across mods ===")
    print(f"{'key':<32} {'type':<8} {'ae':>6} {'cradle':>8} {'aom':>6} {'uses':>6}  sample")
    print("-" * 90)
    for k, ft, ae, cradle, aom, uses, sample in rows:
        s = (sample or '')[:30]
        print(f"{k:<32} {ft:<8} {ae:>6} {cradle:>8} {aom:>6} {uses:>6}  {s}")
    return rows


units_schema   = print_schema('units')
advance_schema = print_schema('advance')
uniticon_schema = print_schema('uniticon')


def write_schema_csv(file_type: str, rows):
    out = CSV_DIR / f"{file_type}_schema_matrix.csv"
    with open(out, 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f)
        w.writerow(['key', 'field_type', 'ae_count', 'cradle_count', 'aom_count', 'uses', 'sample'])
        for row in rows:
            w.writerow(row)
    print(f"  wrote {out.name}")


write_schema_csv('units', units_schema)
write_schema_csv('advance', advance_schema)
write_schema_csv('uniticon', uniticon_schema)

# ------------------------------------------------------------------
# 3. Parse current MoM generated output and compare against schema
# ------------------------------------------------------------------

# Add ctp2_roundtrip to path
sys.path.insert(0, str(TOOLS))
from ctp2_roundtrip import parse_file, export_csv

MOM_GAMEDATA = TOOLS.parent / 'scen0000' / 'default' / 'gamedata'

print("\n\n=== MoM generated output: field coverage vs reference schema ===")

for fname, file_type in [("Units.txt", "units"), ("Advance.txt", "advance"), ("uniticon.txt", "uniticon")]:
    p = MOM_GAMEDATA / fname
    if not p.exists():
        print(f"SKIP {fname} — not found")
        continue

    text = p.read_text(encoding='utf-8', errors='replace')
    blocks = parse_file(text)

    # Load into DB under mod='mom'
    db.execute("DELETE FROM eav_data WHERE mod='mom'")
    rows = []
    for block_id, items in blocks.items():
        for seq, item in enumerate(items):
            from ctp2_roundtrip import KV, Flag, SubList, Nested
            if isinstance(item, KV):
                rows.append(('mom', file_type, block_id, seq, 'kv', item.key, item.val))
            elif isinstance(item, Flag):
                rows.append(('mom', file_type, block_id, seq, 'flag', item.name, ''))
            elif isinstance(item, SubList):
                rows.append(('mom', file_type, block_id, seq, 'sublist', item.key, item.val))
            elif isinstance(item, Nested):
                rows.append(('mom', file_type, block_id, seq, 'nested', item.name, ''))
    db.executemany("INSERT INTO eav_data VALUES (?,?,?,?,?,?,?)", rows)
    db.commit()

    print(f"\n--- {fname}: {len(blocks)} blocks, {len(rows)} fields ---")

    # MoM-only blocks (new ones we added, not in base)
    mom_blocks = set(blocks.keys())
    base_q = db.execute(
        "SELECT DISTINCT block_id FROM eav_data WHERE mod='ae' AND file_type=?",
        (file_type,)
    ).fetchall()
    ref_baseline_blocks = {r[0] for r in base_q}
    new_blocks = sorted(mom_blocks - ref_baseline_blocks)
    print(f"  New blocks (MoM additions): {len(new_blocks)}")

    # For each new MoM block, check what reference fields it's missing
    ref_required = db.execute("""
        SELECT key, field_type, COUNT(DISTINCT mod) mods_present
        FROM eav_data
        WHERE file_type=? AND mod IN ('ae','cradle','aom')
        GROUP BY key, field_type
        HAVING mods_present >= 2
        ORDER BY mods_present DESC
    """, (file_type,)).fetchall()
    required_keys = {(r[0], r[1]) for r in ref_required}  # (key, field_type) present in >=2 mods

    coverage_issues = []
    for bid in new_blocks:
        block_keys = db.execute(
            "SELECT key, field_type FROM eav_data WHERE mod='mom' AND block_id=? AND file_type=?",
            (bid, file_type)
        ).fetchall()
        block_key_set = set(block_keys)
        missing = [(k, ft) for k, ft in required_keys if (k, ft) not in block_key_set]
        if missing:
            coverage_issues.append((bid, missing))

    if coverage_issues:
        print(f"  Blocks missing required fields ({len(coverage_issues)}):")
        for bid, missing in coverage_issues[:10]:
            print(f"    {bid}: missing {[k for k,_ in missing[:5]]}")
    else:
        print(f"  All new blocks have required fields PASS")

    # Fields in MoM blocks that appear nowhere in reference mods (suspicious)
    mom_keys_q = db.execute("""
        SELECT DISTINCT key, field_type FROM eav_data
        WHERE mod='mom' AND file_type=?
    """, (file_type,)).fetchall()
    ref_keys_q = db.execute("""
        SELECT DISTINCT key, field_type FROM eav_data
        WHERE file_type=? AND mod IN ('ae','cradle','aom')
    """, (file_type,)).fetchall()
    mom_keys = {(r[0], r[1]) for r in mom_keys_q}
    ref_keys  = {(r[0], r[1]) for r in ref_keys_q}
    unknown_keys = mom_keys - ref_keys
    if unknown_keys:
        print(f"  Fields in MoM not seen in ANY reference mod ({len(unknown_keys)}):")
        for k, ft in sorted(unknown_keys)[:15]:
            print(f"    {ft:<8} {k}")
    else:
        print(f"  No unknown fields — all field names seen in reference mods PASS")

db.close()
print("\nDone.")
