"""Build proxy recommendation matrix.

For each MoM unit with wrong art, find the best matching candidates from
LotR and HoMM2 based on description similarity.
"""
import json
import re
from pathlib import Path

RESULTS_PATH = Path(__file__).parent / "art_audit_results.json"
OUT_PATH = Path(__file__).parent / "proxy_recommendations.md"

# What each wrong unit SHOULD look like (human-specified intent)
WANTED = {
    "Priest": "robed priest healer holy staff divine",
    "Death Knight": "dark armored knight mounted skeleton undead horse",
    "Lich": "skeletal mage undead robes glowing staff necromancer",
    "Dwarf Warrior": "short stocky dwarf warrior axe shield armor",
    "Dwarf Runesmith": "dwarf mage runes glowing hammer armor",
    "Apprentice": "young mage student robes staff spellcaster",
    "Crystal Golem": "large humanoid construct crystal translucent golem",
    "Djinn": "floating genie spirit ethereal blue magic lamp",
    "Bone Golem": "large construct made of bones golem skeletal",
    "Goblin": "small green goblin creature menacing dagger",
    "Orc": "large green humanoid warrior brutish orc axe",
    "Ogre": "massive brutish humanoid club ogre",
    "Settler": "civilian pioneer cart wagon tools farmer",
    "Caravan": "trade wagon pack mule donkey merchant goods",
    "Dracolich": "skeletal dragon undead bones wings flying",
    "Efreet": "fire genie djinn flame elemental floating",
    "Arch Mage": "powerful mage wizard robes staff magic",
}


def tokenize(text):
    """Simple word tokenizer."""
    return set(re.findall(r'[a-z]+', text.lower()))


def score_match(wanted_tokens, description):
    """Score how well a description matches wanted keywords. Higher = better."""
    desc_tokens = tokenize(description)
    if not desc_tokens or not wanted_tokens:
        return 0
    # Jaccard-ish: count shared tokens weighted by specificity
    shared = wanted_tokens & desc_tokens
    # Bonus for specific fantasy keywords
    fantasy_bonus = {"skeleton", "dragon", "undead", "dwarf", "golem", "mage",
                     "priest", "knight", "goblin", "orc", "ogre", "genie",
                     "spirit", "elemental", "fire", "holy", "divine", "mounted",
                     "horse", "robed", "staff", "axe", "shield", "bow",
                     "floating", "winged", "construct", "bones", "wagon"}
    bonus = len(shared & fantasy_bonus) * 0.5
    return len(shared) + bonus


def main():
    with open(RESULTS_PATH, encoding="utf-8") as f:
        data = json.load(f)

    # Build candidate pool from LotR + HoMM2
    candidates = []
    for item in data.get("lotr", []):
        desc = item.get("description", "")
        if "ERROR" in desc or "PARSE_FAIL" in desc:
            continue
        candidates.append({
            "source": "lotr",
            "name": item["name"],
            "file": item.get("file", ""),
            "description": desc,
        })

    for item in data.get("homm2", []):
        desc = item.get("description", "")
        if "ERROR" in desc or "PARSE_FAIL" in desc:
            continue
        candidates.append({
            "source": "homm2",
            "name": item["name"],
            "description": desc,
        })

    print(f"Candidate pool: {len(candidates)} ({sum(1 for c in candidates if c['source']=='lotr')} LotR, "
          f"{sum(1 for c in candidates if c['source']=='homm2')} HoMM2)")

    # For each wrong unit, rank candidates
    lines = ["# Proxy Recommendations\n"]
    lines.append("For each MoM unit with wrong art, the top 5 candidates from LotR/HoMM2.\n")
    lines.append("Generated by matching vision model descriptions against wanted keywords.\n")

    for unit_name, wanted_desc in sorted(WANTED.items()):
        wanted_tokens = tokenize(wanted_desc)

        scored = []
        for c in candidates:
            s = score_match(wanted_tokens, c["description"])
            if s > 0:
                scored.append((s, c))

        scored.sort(key=lambda x: -x[0])
        top5 = scored[:5]

        lines.append(f"\n## {unit_name}\n")
        lines.append(f"**Wanted:** {wanted_desc}\n")
        lines.append("| Score | Source | ID | Description |")
        lines.append("|-------|--------|-----|-------------|")
        for score, c in top5:
            src = c["source"]
            name = c["name"]
            file_ref = c.get("file", "")
            desc = c["description"][:80]
            lines.append(f"| {score:.1f} | {src} | {name} ({file_ref}) | {desc} |")

        if not top5:
            lines.append("| — | — | — | No matches found |")

    # Write
    out_text = "\n".join(lines) + "\n"
    OUT_PATH.write_text(out_text, encoding="utf-8")
    print(f"\nWrote {OUT_PATH}")
    print(f"\n{'='*60}")
    # Print summary
    for unit_name in sorted(WANTED.keys()):
        wanted_tokens = tokenize(WANTED[unit_name])
        best = None
        best_score = 0
        for c in candidates:
            s = score_match(wanted_tokens, c["description"])
            if s > best_score:
                best_score = s
                best = c
        if best:
            print(f"  {unit_name:20s} -> {best['source']:5s} {best['name']:10s} "
                  f"(score {best_score:.1f}): {best['description'][:50]}")


if __name__ == "__main__":
    main()
